config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :tweets do 
  	collection do 
  	end
  end

  root :to => 'tweets#index'
  
  
  get "/auth/:provider/callback" => "sessions#create"
  
  delete "/signout" => "sessions#destroy", :as => :signout
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def create
    auth = request.env["omniauth.auth"]
    p "--------------__#{auth.inspect}"
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
  
  
end

app/controllers/tweets_controller.rb
require 'idol_api'
require 'twitter_api'

class TweetsController < ApplicationController
	include IdolApi
	include TwitterApi

	TWEET_COUNT = 500
	
	def index
		# Configure the number of tweets to be fetched in the TWEET_COUNT.
			# Set the max_id value (last tweet's id) and use it to get the next set of tweets.
	    @positive_result = []
	    @negative_result = []
	    @neutral_result = []
	    counter = 0
			@tweets = search_tweets(params[:hashtag], param_values(params))#.take(TWEET_COUNT)
			# render json: @tweets
			@tweets.each do |tweet|
				sentimental = get_sentimental(tweet.text)
				@positive_result << tweet.as_json.merge!(sentimental: sentimental) if sentimental[:sentiment] == "positive"
				@negative_result << tweet.as_json.merge!(sentimental: sentimental) if sentimental[:sentiment] == "negative"
				@neutral_result << tweet.as_json.merge!(sentimental: sentimental) if sentimental[:sentiment] == "neutral"
				counter+=1
			end
			@positive_percent = (@positive_result.count * 100 )/counter
			@negative_percent = (@negative_result.count * 100 )/counter
			@neutral_percent = (@neutral_result.count * 100 )/counter
			p "--------#{counter}"
	end

	def show
		@tweet = fetch_tweet(params[:id])
		@language = JSON.parse identify_language(@tweet.text)
		@sentiment = JSON.parse detect_sentiment(@tweet.text, @language)
		
		# Positive terms in the tweet
		@positive_terms = @sentiment["positive"].sort_by{ |hsh| hsh["score"] }.reverse
		positive_sentiment_terms = @positive_terms.collect{ |hsh| hsh["sentiment"] }		
		@pos_highlighted_tweet = JSON.parse(highlight_text(
			@tweet.text, positive_sentiment_terms, "<span class='pos_highlight'>"))
		
		# Negative terms in the tweet
		@negative_terms = @sentiment["negative"].sort_by{ |hsh| hsh["score"] }.reverse
		negative_sentiment_terms = @negative_terms.collect{ |hsh| hsh["sentiment"] }
		@neg_highlighted_tweet = JSON.parse(highlight_text(
			@tweet.text, negative_sentiment_terms, "<span class='neg_highlight'>" ))
	end


	private
		def param_values(params)
			{
				:since_date => start_date(params),
				:until_date => end_date(params),
				:max_id => params[:max_id],  # This param fetches tweets older than the given tweet ID
				:include_rts => params[:include_rts]
			}
		end

	  def start_date(params)
	    parse_from_date(params) ? Time.parse(parse_from_date(params)) : (Time.now.ago 30.day)
	  end
	  
	  def end_date(params)  
	    parse_to_date(params) ? Time.parse(parse_to_date(params)).end_of_day : Time.now
	  end
	  
	  def parse_from_date(params)
	    (params[:date_range].split(" - ")[0]) || params[:date_range] unless params[:date_range].blank?
	  end
	  
	  def parse_to_date(params)
	    (params[:date_range].split(" - ")[1]) || params[:date_range] unless params[:date_range].blank?
	  end

	  def get_sentimental text
			analyzer = Sentimental.new
			analyzer.load_defaults
			sentiment = analyzer.sentiment text
			score = analyzer.score text
			data = {sentiment: sentiment.to_s, score: score}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def formated_date(date)
    date.to_datetime.strftime('%b %d, %Y')
  end

  def format_float_value(val)
    if !(val.is_a? Fixnum)
      sprintf( "%0.01f", val)
    else
      return val.to_s
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_image(sentiment)
		if sentiment == "positive"
			return "positive.png"
		elsif sentiment == "negative"
			return "negative.png"
		elsif sentiment == "neutral"
			return "neutral.png"
		end	
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpinionMiner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		
		<% if current_user %>
		  Welcome <%= current_user.name %>!
		  <%= link_to "Sign Out", signout_path %>
		<% else %>
		  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
		<% end %>
		
		
    <%= yield %>
  </body>
</html>

app/views/tweets/_tweets.html.erb
<div class="span13">
	<% if results.present? %>
		<table id="" class="table table-striped table-hover">
		  <tr>
		    <th width="45%">Tweet</th>
		    <th width="20%">Created at</th>
		    <th width="20%">Sentiment</th>
      <th width="20%">Sentiment score</th>
		  </tr>
		  <% results.each do |tweet| %>
		    <tr>
					<td class="tweet"><%= link_to(tweet["text"], tweet_path(tweet["id"])) %></td>
					<td class="tweet_created"><%= tweet["created_at"] %></td>		
					<td class="sentiment"><%= tweet[:sentimental][:sentiment] %></td>
									
					<td class="sentiment"><%= image_tag get_image(tweet[:sentimental][:sentiment]) %></td>
        <td class="sentiment_score"><%= tweet[:sentimental][:score].round(2) %></td>
		    </tr>
      <% @max_id = tweet["id"] %>
		  <% end %>
		</table>
  <%= link_to "More", tweets_path({:hashtag => params[:hashtag], :date_range => params[:date_range], 
    :max_id => @max_id}), :class => "pull-right" %>
	<% else %>
		No tweets were found.
	<% end %>	
</div>

app/views/tweets/index.html.erb
<div class="container">
  <br>
  <%= form_tag tweets_path, :id => "tweets_filter", :method => :get do %>
  	<% default = params[:hashtag].blank? ? "@quovantis" : params[:hashtag] %>

    <%= text_field_tag :hashtag, params[:hashtag], :value => default %>
   
   	<%#= text_field_tag :date_range, "" %>

    <%= submit_tag "view",:class => "btn btn-primary", :id => "tweet_btn", "data-loading-text" => "Fetching" %><br>
    
    <%#= check_box_tag :include_rts, params[:include_rts], params[:include_rts] %> 
  <% end %>
	<div>
   <span>Positive: <%=  @positive_percent.to_s+"%"%></span>,<span>Negative: <%=  @negative_percent.to_s+"%"%></span>,<span>Neutral: <%=  @neutral_percent.to_s+"%"%></span>
  </div>

  <br>
    <h4>Positive Tweets</h4>
    <%= render partial: "tweets", locals: { results: @positive_result } %> 
    <h4>Negative Tweets</h4>
    <%= render partial: "tweets", locals: { results: @negative_result } %>  
    <h4>Neutral Tweets</h4>
    <%= render partial: "tweets", locals: { results: @neutral_result } %>   
</div>



<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery("#date_range").daterangepicker({
      earliestDate: Date.parse('1/12/2013'),
      latestDate: new Date(),
      presetRanges: [      
        {text: "Last 2 days", dateStart: 'Today-3', dateEnd: 'Today' },
        {text: "Last 7 days",dateStart: 'Today-8',  dateEnd: 'Today'}
      ],
      presets: {
        dateRange: "Custom filter"
      },
      dateFormat: 'dd M yy',
      closeOnSelect: true,
      onClose: function() {
        jQuery('#date_range').trigger('change');
      }
    });
    <% if params[:date_range].present? %>
      jQuery("#date_range").val('<%= params[:date_range] %>');   
    <% else %>
      jQuery("#date_range").val('<%= 7.days.ago.strftime("%d %b %Y") %> - <%= Time.now.strftime("%d %b %Y") %>')
    <% end %>


    jQuery('#date_range').bind('keypress keyup keydown', function(ev) {
      ev.preventDefault();
      return false;
    });
  });
  
  // $(window).bind("load", function() {
 //
 //    $(".language").each(function() {
 //      $(this)[0].innerHTML = "Loading..."
 //      processApi($(this), $(this), "identifylanguage")
 //    });
 //
 //
 //    $(".sentiment").each(function() {
 //      score_element = $(this).siblings(".sentiment_score") ;
 //      score_element[0].innerHTML = "Loading..."
 //      $(this)[0].innerHTML = "Loading..."
 //      processApi($(this), score_element, "detectsentiment")
 // 		});
 //
 //  });
 //
 //  processApi = function(element, score_element, api){
 //    var text =  element.siblings(".tweet").children("a")[0].innerHTML;
 //
 //    var expression = /[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi;
 //    var regex = new RegExp(expression);
 //    var links = text.match(regex)
 //
 //    if(links){
 //      $.each(links, function(index, value){ text = text.replace(value, "") });
 //    }
 //    text = text.replace(/#/g, "")
 //
 //    var base_url = "<%#= IdolApiConfig["url"] %>/" + api + "/<%#= IdolApiConfig["version"] %>"
 //    var url = base_url + "?apikey=" + "<%#= IdolApiConfig["api_key"] %>" + "&text=" + text + "ex"
 //    console.log(url);
 //    url = encodeURI(url);
 //
 //    $.getJSON(url, {}, function(result){
 //      if(api === "detectsentiment"){
 //        score_element[0].innerHTML = (result.aggregate.score*100).toFixed(2) + "%";
 //        displayIcon(element, result.aggregate.sentiment)
 //      }
 //      if(api === "identifylanguage"){
 //        element[0].innerHTML = result.language;
 //      }
 //    });
 //  };
 //
 //  displayIcon = function(element, sentiment){
 //    if(sentiment === "positive"){
 //      element[0].innerHTML = "<img src='/assets/positive.png' />"
 //    }
 //    if(sentiment === "negative"){
 //      element[0].innerHTML = "<img src='/assets/negative.png' />"
 //    }
 //    if(sentiment === "neutral"){
 //      element[0].innerHTML = "<img src='/assets/neutral.png' />"
 //    }
 //  }
  
  jQuery('#tweets_filter').submit(function () {
    if (jQuery(this).valid()) {      
      jQuery("#tweet_btn").button('loading');
    }
  });

</script>


app/views/tweets/show.html.erb
<div class="container mtop" id="tweet-details">

  <%= link_to("< Back", tweets_path, :class => "add-note") %>
  
    <div id="content-header">
      <h6>Tweet ID #<%= @tweet.id %></h6>
    </div>
    
    <div class="tweet-content">
      <ul>
        <li><span>Tweet text</span><br><%= @tweet.text %></li>
        <li><span>User Name</span><br><%= @tweet.user.name %></li>
        <li><span>Public URL</span><br><a href=<%= @tweet.url.to_s %> target="_blank"><%= @tweet.url %></a></li>
        <li><span>Created at</span><br><%= formated_date(@tweet.created_at) %></li>
        <li><span>Language</span><br><%= @language["language"].to_s.titleize  %></li>
        
        
        <li><span>Sentiment type</span><br>
          <% if @sentiment["aggregate"]["sentiment"] == "positive"  %>
            <img src='/assets/positive.png' />
          <% elsif @sentiment["aggregate"]["sentiment"] == "negative"  %>
            <img src='/assets/negative.png' />
          <% elsif @sentiment["aggregate"]["sentiment"] == "neutral"  %>
            <img src='/assets/neutral.png' />
          <% end %>
        </li>

        <li><span>Sentiment Score</span><br><%= format_float_value(@sentiment["aggregate"]["score"]) %></li>
      </ul>      
    </div><br>
        

    <div id="content-header">        
      <h6>Positive terms in the tweet</h6>
    </div>
      
    <div class="tweet-content">
      <% if @positive_terms.present? %>
        <ul>
          <li><%= @pos_highlighted_tweet["text"].html_safe %></li>
        </ul>
        <br><br>

        <table class="table table-striped table-hover">
          <tr>
            <th width="20%">Top 5 terms</th>
            <th width="45%">Original text</th>
            <th width="15%">Score</th>
          </tr>
          <% @positive_terms[0..4].each do |term| %>
            <tr>
              <td><%= term["sentiment"] ? term["sentiment"] : "N/A"  %></td>
              <td><%= term["original_text"] %>
              <td><%= format_float_value(term["score"]) %></td>
            </tr>
          <% end %>          
        </table>
      <% else %>
        <p>No positive terms in the tweet.</p>
      <% end %>
    </div>
    

    <div id="content-header">        
      <h6>Negative terms in the tweet</h6>
    </div>
      
    <div class="tweet-content">
      <% if @negative_terms.present? %>
        <ul>
          <li><%= @neg_highlighted_tweet["text"].html_safe %></li>
        </ul>
        <br><br>

        <table class="table table-striped table-hover">
          <tr>
            <th width="30%">Top 5 terms</th>
            <th width="20%">Score</th>
          </tr>
          <% @negative_terms[0..4].each do |term| %>
            <tr>
              <td><%= term["sentiment"] ? term["sentiment"] : "N/A" %></td>
              <td><%= term["original_text"] %>
              <td><%= format_float_value(term["score"]) %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>No negative terms in the tweet.</p>
      <% end %>
    </div>
    
    
  </div>
</div>